# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5090396d83393cf20acb6f073cfd01fc6330ccf8d85481e787c63cd88249f9b4aea6d223e185cbb80acc9d51089c36e2f312e197a98fde563f52145945cae1

test:
  secret_key_base: 5cefcd347794d32a1e9fd3f4e35044d2539c91510e04ecc920ee27d19b0f6b1e38969e943e664ae5e69af9005d94243ee02b251f2cd3067569e32d79c0620320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
